version: '3'

services:
    web:
        image: nginx:latest
        restart: always   
        ports:
            - "8080:80"
        depends_on:
          - php
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        #image: php:fpm
        build: .
        restart: always
        depends_on:
          - database
        links:
          - database
        volumes:
            - ./code:/code
    database:
        image: mysql:5.7
        #restart: always
        volumes:
            - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: dock
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        #command: --init-file /data/application/schema.sql
        